import Header from "./Components/Navbar/Header";
import Navbar from "./Components/Navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-[1400px] mx-auto">
        <Header />
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
